# Generated by Django 2.0.13 on 2019-06-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=30)),
                ('b', models.DateTimeField()),
                ('c', models.TextField()),
                ('d', models.IntegerField()),
            ],
        ),
    ]
